### ISSUE TITLE
doesnt open

### ISSUE THREAD

**Issue by marcelo4768** [utsanjan/PD-Runner#14]
m1 app doesnt open
<img width="328" alt="Captura de Pantalla 2022-09-02 a la(s) 03 21 25" src="https://user-images.githubusercontent.com/50896780/188082004-aef47778-fedc-44d7-a17c-38514dabc180.png">

**Comment by utsanjan** [comment]
You should first of all enable the trial period directly from Parallels Desktop app. PD runner just skips the 'trial is over' pop up, so it needs it to be enabled manually first.

**Comment by marcelo4768** [comment]
trial preriod is end, go direct to buy or serial windows
