### ISSUE TITLE
Issues with PDrunner

### ISSUE THREAD

**Issue by NataliaShlenskaya** [utsanjan/PD-Runner#16]
Hello! Recently I faced with issue that VM pauses every 1-2 minutes and I need to restart it with PDrunner every time which makes me feel very nervous(( Too often this bag happens! Could you please tell what to do with it?

**Comment by utsanjan** [comment]
This issue is fixed now in the new 0.3.8 patched version. And yes, do follow the new usage guide from the ReadMe for it to work perfectly.
