### ISSUE TITLE
Still see the trial allert about genuine copy((

### ISSUE THREAD

**Issue by erma4ina** [utsanjan/PD-Runner#17]
Hi there and many thanx about ur materials!! I have been founding issues to start PD-Runner for some time, but there were only forums, where experienced specialists only consider why it happens without giving exact instructions what to do)

But unfortunately after having success with starting PD-Runner I have the same issue about genuine copy(( So, here is my screens info.

Parallels Desktop info says that my copy is activated, and next activation is set to 09.05.2045
<img width="1792" alt="Снимок экрана 2022-09-12 в 14 02 16" src="https://user-images.githubusercontent.com/102543402/189641299-1417865b-396b-402a-917f-9f19a65c2190.png">
<img width="1792" alt="Снимок экрана 2022-09-12 в 14 03 17" src="https://user-images.githubusercontent.com/102543402/189641334-16b72851-899d-4b12-bf51-fe30a60fbdce.png">

So, if u can give the cue bout what I`m doing wrong or what happens - it would be great) Cause principally want to understand whats happening here))

Thank U!)

**Comment by utsanjan** [comment]
This issue is fixed now in the new 0.3.8 patched version. And yes, do follow the new usage guide from the ReadMe for it to work perfectly.

**Comment by erma4ina** [comment]
Thank u, but after installing patch my parallels desktops falled down and doesn't even starts((((

I opened new issue
