### ISSUE TITLE
PD Runner not working on Monterey 12.6

### ISSUE THREAD

**Issue by SB99-07** [utsanjan/PD-Runner#18]
I get the following error message when running 0.3.8
Please advise.... 
<img width="258" alt="Screenshot 2022-09-13 at 23 49 05" src="https://user-images.githubusercontent.com/66477109/190015566-8725f9af-43ce-41d1-9e10-09751be93bff.png">

**Comment by wderdari** [comment]
Read the "Frequently Asked Questions" and follow the steps there.
