### ISSUE TITLE
Unable to connect to parallels service

### ISSUE THREAD

**Issue by YTF1shhh** [utsanjan/PD-Runner#22]
I installed everything according to the directions. When I try to run the VM with PD Runner I get 2 pop-ups that are exactly the same.

They look like this
<img width="488" alt="Screenshot 2022-09-17 at 10 18 39 PM" src="https://user-images.githubusercontent.com/66437973/190886951-a16f3bd3-9f1e-48e8-8f13-fed93ea96c49.png">

I'm on the latest version of parallels and I'm on the MacOs Ventura 13.0 Beta
I've also tried the suggested fixes that parallels says to do.

**Comment by utsanjan** [comment]
May I know which version of Parallels are you on?
