### ISSUE TITLE
new patch does not starts and damaged my Parallels Desktop, so it don't starts too, HELP!!

### ISSUE THREAD

**Issue by erma4ina** [utsanjan/PD-Runner#24]
After doing all steps from readme file, PD Runner asks my pass, then simply disappears! It stays in processes but not in menu bar and nothing happens. I managed to install PD Runner twice - the same issue. And more serious problem that my Parallels Desktop doesn't starts too now, it's a big shame and problem cause I have one of my work on it! HELP!!

here is all needed screens
<img width="1792" alt="Снимок экрана 2022-09-19 в 17 44 57" src="https://user-images.githubusercontent.com/102543402/191047749-6e174d6f-3fd8-49f7-8b1c-84617ede8365.png">
<img width="1792" alt="Снимок экрана 2022-09-19 в 17 45 59" src="https://user-images.githubusercontent.com/102543402/191047757-63980146-7af2-4e55-8bf8-830586d3a452.png">

**Comment by utsanjan** [comment]
Upgrade it to parallels 18 directly and then follow the same steps mentioned in the ReadMe. Everything should be fixed.

**Comment by erma4ina** [comment]
How can I upgrade it, if it doesn't starts?

**Comment by utsanjan** [comment]
You can just download the [Parallels Desktop](https://www.parallels.com/) DMG from the official website and then install it directly without uninstalling the previous one.

**Comment by erma4ina** [comment]
I managed to download it from here https://appstorrent.ru/61-parallels-desktop.html while ur answering - and now its all works!)) Thank u a lot for ur help and fast answers!!! I had some panic about my work on tenders, where I should be in touch all time)) U re my hero!)) I need some time to look after it if the trial issue is fixed and it won't show me window about genuine copy, but hope its ok! Thank U!!
<img width="1792" alt="Снимок экрана 2022-09-19 в 18 54 17" src="https://user-images.githubusercontent.com/102543402/191060202-c0b8f841-fc3c-421a-afe6-1cf8cbe26052.png">

**Comment by erma4ina** [comment]
yes, its all works! approooved!
