### ISSUE TITLE
0.3.8 patched is in fact the permanent license crack

### ISSUE THREAD

**Issue by fcps3** [utsanjan/PD-Runner#26]
I noticed that you used the patch script that cracks parallels adding a permanent license, in fact after executing "sudo chmod +x /Applications/PD\ Runner.app/patch && sudo sh /Applications/PD\ Runner.app/patch" pd runner is no more needed
It should be correct to say this in readme, and also to suggest host/firewall/dns lock like has been done here
https://notabug.org/somebasj/ParallelsDesktopCrack

Locks in host file is secure only if after you lock the file, parallels has starded editing it

**Comment by utsanjan** [comment]
Exactly you are right, I'll add this in the ReadMe. The thing is that uploading the patch script separately without embedding it in the application itself would increase the chances of getting a DMCA strike just like the original GitHub repo of [sombasej](https://github.com/somebasj/):

https://github.com/somebasj/ParallelsDesktopCrack
