### ISSUE TITLE
Make sure you are already a trial user (even if it is expired) Then restart your Mac and try again.

### ISSUE THREAD

**Issue by DmitryLebovski** [utsanjan/PD-Runner#27]
Hello! Thanks for creating PD Runner! Its incredably helped me a lot. I wanted to reinstall Parallels, did everything right, installed PD Loader, but it says "Failed to start! Make sure you are already a trial user (even if it is expired) Then restart your Mac and try again." I restarted mac many times, reinstalled pd runner, did everything throw terminal, nothing helped. Can you help solve this out?

**Comment by utsanjan** [comment]
Which version of Parallels Desktop are you using?

**Comment by vahid-saeed** [comment]
same problem here, it was working but suddenly trial has been finished and I got "Failed to start! Make sure you are already a trial user (even if it is expired) Then restart your Mac and try again."  Parallel Desktop Version 18.0.2 (53077) with last PD runner

**Comment by utsanjan** [comment]
Can you try the patch command once more? Let me know what happens.

**Comment by vahid-saeed** [comment]
> Can you try the patch command once more? Let me know what happens.

Let me how I will do it

**Comment by vahid-saeed** [comment]
Now it is working , Thanks

**Comment by DmitryLebovski** [comment]
Thanks you a lot! Its working now!!!
