### ISSUE TITLE
Unable to connect to Parallels service - Parallels 18

### ISSUE THREAD

**Issue by WeGoToMars** [utsanjan/PD-Runner#30]
I have the latest version of both PD Runner and Parallels, active trial, and I've already reinstalled and re-run the patch command for PD runner. Still, I'm getting this error. What could be the fix?

<img width="859" alt="image" src="https://user-images.githubusercontent.com/47947772/192404179-92c2e198-eaf0-4691-8ba6-a2187cd5afc3.png">

Thank you!

**Comment by utsanjan** [comment]
Have you tried restarting your mac once after all the installation steps?

**Comment by WeGoToMars** [comment]
I've just done it, and nothing has changed

**Comment by utsanjan** [comment]
Now try running the Parallels Desktop directly.

**Comment by WeGoToMars** [comment]
Still, no change, the menu bar app lists that it can't connect to the service. However, the license section now lists "Permanent business licence," and I don't get the trial popup. Is this the intended behavior?

**Comment by utsanjan** [comment]
Somewhat yes, actually the PD Runner should've worked. But, anyways after introducing the patch which basically replaces the existing trial license with a permanent business license, you can use it without actually running it via PD Runner.
