### ISSUE TITLE
Issue with running 18.1

### ISSUE THREAD

**Issue by vahid-saeed** [utsanjan/PD-Runner#42]
I updated the Parallel desktop to 18.1.0 and unfortunately, after applying crack windows stuck in a reboot loop, I tried to update Parallel tools in safe mode it also was unsuccessful the error was about pdfm18_en_US_PToolsRollback, I downgrade to 18.0.3 it is working.

**Comment by vahid-saeed** [comment]
Only windows 11 has boot loop problem. but Linux kali doesn't have any problem, it boots up normaly and Parallel tools install without problem.

**Comment by utsanjan** [comment]
Got you, will roll out an update soon

**Comment by utsanjan** [comment]
> Only windows 11 has boot loop problem. but Linux kali doesn't have any problem, it boots up normaly and Parallel tools install without problem.

I've released a new patch for PD Runner that fixes this. Hope that works, do let me know if you face any more issues.
