### ISSUE TITLE
already patched

### ISSUE THREAD

**Issue by dagfreak111** [utsanjan/PD-Runner#44]
![ 2022-11-05 11 44 12] (https://user-images.githubusercontent.com/116982636/200101639-1c7644d3-387c-4764-b01e-644b7e95e198.jpg)
MacBook Air m1, macOS Ventura 13.0, pd runner 18.1.0

**Comment by utsanjan** [comment]
As per I've said in the readme, try re-installing parallels. You don't have to uninstall it, just install the dmg on top of it. Then try the procedure again.
