### ISSUE TITLE
PD Runner not installing 

### ISSUE THREAD

**Issue by AYMAAN69** [utsanjan/PD-Runner#45]
Hi. The latest version of pd runner isnt working for me , it doesnt install . when I updated to the latest parallels 18 , pd runner stopped working . so i decided to uninstall pd runner and reinstall the latest one . but it doesnt work 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/63039737/200371545-bbb704db-8bab-48c8-b287-66712a12e114.png">

and then this : 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/63039737/200371614-60e07946-1fcd-4f99-aaf1-b9cf1fab5c49.png">

**Comment by AYMAAN69** [comment]
> Can you show me the error you face after updating Parallels? And please mention your current parallels ver no.

the error is the aformentioned and this 

since I deleted pd runner i cant show you the error , however I am unable to isntall it as the installation keeps failing

**Comment by Ninjaswordfish46** [comment]
Have you tried updating to the latest version of parallels? I had this issue until I updated to Version 18.1.0

**Comment by AYMAAN69** [comment]
yes updating it worked , its fixed now . but there i dont have the pd runner app anymore it just patches it and gives me a business license

**Comment by utsanjan** [comment]
> yes updating it worked , its fixed now . but there i dont have the pd runner app anymore it just patches it and gives me a business license

Yes, that's what the new version does. It doesn't have any menubar or launcher activity.
