### ISSUE TITLE
Error: Already patched!

### ISSUE THREAD

**Issue by I024px** [utsanjan/PD-Runner#47]
<img width="622" alt="Snipaste_2022-11-08_14-58-23" src="https://user-images.githubusercontent.com/34879422/200496176-ae1ff6de-80f5-4759-bd84-c5682ac92249.png">
<img width="622" alt="Snipaste_2022-11-08_14-58-34" src="https://user-images.githubusercontent.com/34879422/200496192-2d8ac22f-7d3f-403f-93b3-2408cfe5a9c3.png">

**Comment by utsanjan** [comment]
As per I've said in the readme, try re-installing parallels. You don't have to uninstall it, just install the dmg on top of it. Then try the procedure again.
