### ISSUE TITLE
Error Patched 

### ISSUE THREAD

**Issue by AYMAAN69** [utsanjan/PD-Runner#48]
after installing pd runner it shows this

<img width="251" alt="image" src="https://user-images.githubusercontent.com/63039737/200582083-2dcec692-18cb-47b4-9c9e-fcad1e919015.png">

and then this : 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/63039737/200582140-ee3e5b90-2bfb-4432-87c6-2b8cd630b015.png">

please help

**Comment by utsanjan** [comment]
As per I've said in the readme, try re-installing parallels. You don't have to uninstall it, just install the dmg on top of it. Then try the procedure again.
