### ISSUE TITLE
“pd.command” can’t be opened because Untitled is not allowed to open documents in Terminal.

### ISSUE THREAD

**Issue by wikwity** [utsanjan/PD-Runner#49]
<img width="328" alt="Screenshot 2022-11-08 at 5 44 52 PM" src="https://user-images.githubusercontent.com/38224978/200624934-c8de1a3f-2e51-4a41-95d4-6e9c78e33a5b.png">

PD-Runner 18.1.0, MacOS Ventura, Parallels Desktop 18.1.0, tried to reinstall Parallels Desktop first, after that running PD-Runner and it's still doesn't work

**Comment by utsanjan** [comment]
Can you please try re-downloading the PD runner 18.1.0 (I've updated the release just now), cuz I uploaded a test version by mistake and it is still buggy.

**Comment by wikwity** [comment]
Now I'm getting this
<img width="372" alt="Screenshot 2022-11-08 at 6 31 44 PM" src="https://user-images.githubusercontent.com/38224978/200635056-2dfef54c-c9d3-43bf-bcc7-e114f5b0ad62.png">

**Comment by utsanjan** [comment]
> Now I'm getting this <img alt="Screenshot 2022-11-08 at 6 31 44 PM" width="372" src="https://user-images.githubusercontent.com/38224978/200635056-2dfef54c-c9d3-43bf-bcc7-e114f5b0ad62.png">

I asked to re-downloading the PD runner 18.1.0 from [here](https://github.com/utsanjan/PD-Runner/releases/tag/18.1.0). You should get ".pkg" file after extracting the zip, not a ".app" file.

**Comment by wikwity** [comment]
> I asked to re-downloading the PD runner 18.1.0 from [here](https://github.com/utsanjan/PD-Runner/releases/tag/18.1.0). You should get ".pkg" file after extracting the zip, not a ".app" file.

That's what I did.

**Comment by wikwity** [comment]
I think I figured it out. PD Runner.pkg install itself into Downloads folder, I had to manually drag it to Applications folder. But we got back to the first issue I described here. Still can't open pd.command file.

**Comment by utsanjan** [comment]
> I think I figured it out. PD Runner.pkg install itself into Downloads folder, I had to manually drag it to Applications folder. But we got back to the first issue I described here. Still can't open pd.command file.

No, you don't have to drag the .pkg file anywhere. Just double-click on the .pkg and go through the installation process. And also this version doesn't have any menubar icon or interface, it just patches the already existing parallels. So lastly open the parallels app directly from your app drawer. Hope this helps.

**Comment by wikwity** [comment]
> And also this version doesn't have any menubar icon or interface, it just patches the already existing parallels.

Now it makes sense. I'm sorry for taking your time, didn't know about this.
