### ISSUE TITLE
cannot find an app icon in launchpad after installation

### ISSUE THREAD

**Issue by NutterLee** [utsanjan/PD-Runner#50]
I am using the latest release, and my os is Ventura 13.0 with M1 Pro.
Thanks.

**Comment by NutterLee** [comment]
Or maybe I can just directly use the parallel app?

**Comment by utsanjan** [comment]
The last version doesn't have any launcher or menubar interface. It patches the parallels desktop app itself. So, launch parallels directly after installation completes.
