### ISSUE TITLE
Can't install PD Runner 18.1.0 

### ISSUE THREAD

**Issue by bri522** [utsanjan/PD-Runner#51]
<img width="342" alt="Captura de pantalla 2022-11-10 a la(s) 15 59 10" src="https://user-images.githubusercontent.com/62036055/201204709-4dd78e8d-c969-44cd-8cd5-1a4a6cebd1ab.png">

I have a MacBook Air M2 
Ventura 13.0

**Comment by utsanjan** [comment]
As per I've said in the readme, try re-installing parallels. You don't have to uninstall it, just install the dmg on top of it. Then try the procedure again.
