### ISSUE TITLE
PD Runner not starting

### ISSUE THREAD

**Issue by TechVid-Kid** [utsanjan/PD-Runner#52]
![Screen Shot 2022-11-11 at 6 41 02 PM](https://user-images.githubusercontent.com/97792135/201444912-2d2bf0b2-db3b-4849-9de9-9372a91bcb6d.png)
Hi there, I have been having an issue recently where pd runner hasnt been launching on my mac. I have tried reinstalling pd runner multiple times with different versions as well, I have also reinstalled parallels desktop with the right version for pd runner. All help would be appreciated!

**Comment by utsanjan** [comment]
Don't use the .app version, instead try using the last .pkg version. It'll patch parallels directly, hence doesn't have any menubar or launcher interface.
