### ISSUE TITLE
Error: Cannot sign app

### ISSUE THREAD

**Issue by CheemsC** [utsanjan/PD-Runner#54]
Hello! For some reason, I get the issue "Error: Cannot Sign App" whenever I try to run the PD Runner .pkg. If I try installing it again, I get the typical "Already Patched" error which is detailed in the readme. When I reinstall Parallels, both by installing on top of the existing application  _and_ by completely uninstalling PD and installing it again, I get the same "cannot sign app" error again. I tried all of the terminal commands listed in the readme, and I still cannot install PD Runner. I would really appreciate some help.

**Comment by CheemsC** [comment]
@utsanjan Would installing xcode command line tools fix this "could not sign" error?
I found on another repo that this can fix a codesign error. Do you think this is the same thing?

**Comment by eat-your-glory** [comment]
Maybe it could help. It sure doesn't do any harm installing those.
