### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by mengchaoheng** [utsanjan/PD-Runner#55]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/43166007/202062826-f777122d-ccfb-4dcc-9bb8-68a614086686.png">

**Comment by eat-your-glory** [comment]
Could you please translate? I don't understand Chinese.

**Comment by eat-your-glory** [comment]
Do you have Parallels Desktop downloaded and installed?

**Comment by mengchaoheng** [comment]
yes I have to reback to pd17 instead of 18

**Comment by eat-your-glory** [comment]
If you wanna use PD 18, download the Newest Version from this Repository
