### ISSUE TITLE
erreur Install

### ISSUE THREAD

**Issue by trickess** [utsanjan/PD-Runner#58]
bonjour 
j'ai rencontré un problème d'install
![Capture d’écran 2022-11-24 à 17 46 02](https://user-images.githubusercontent.com/118999499/203835569-138cb38b-24b1-49bc-9cd5-7646f7b83e3a.png)

**Comment by eat-your-glory** [comment]
Je vais utiliser Google Translate pour ça :

Si vous obtenez une telle erreur, veuillez essayer de réinstaller Parallels Desktop avec le dernier installateur DMG. Ne le désinstallez pas, installez-le simplement au-dessus de l'application déjà existante. Une fois réinstallé, répétez la procédure de correction avec le fichier "PD Runner.
