### ISSUE TITLE
I can't find icon in the menu bar.

### ISSUE THREAD

**Issue by chen1912** [utsanjan/PD-Runner#66]
<img width="480" alt="截屏2022-12-30 11 42 03" src="https://user-images.githubusercontent.com/61451493/210093349-ecf6b5c3-fbbd-45da-af1f-016a78999805.png">
After installation, the menu bar only displays the icon of PD, but I cannot find the icon of PD Runner.

**Comment by WolfHex** [comment]
If you downloaded the pkg version of PD Runner it's normal.
PD Runner (PKG) version only patches PD so if you didn't get any errors you're good to go.

**Comment by WolfHex** [comment]
> <img alt="截屏2022-12-30 11 42 03" width="480" src="https://user-images.githubusercontent.com/61451493/210093349-ecf6b5c3-fbbd-45da-af1f-016a78999805.png">
> After installation, the menu bar only displays the icon of PD, but I cannot find the icon of PD Runner.

If you downloaded the pkg version of PD Runner it's normal.
PD Runner (PKG) version only patches PD so if you didn't get any errors you're good to go.
