### ISSUE TITLE
PD runner does not show in app menu

### ISSUE THREAD

**Issue by creativedoctor** [utsanjan/PD-Runner#69]
I had PD 0.3.8 and Parallels 17.1 before and after going straight to installing 18.1.1 with the new PD version, it does seem patched (does not check for update even) but it doesn't show in the application folder nor I can put it in the menu...
macOS 12.6.2, latest PD and PD runner

**Comment by utsanjan** [comment]
The new versions don't have any menubar or launcher activities. Just running the pkg will patch the parallels application itself. It replaces the free license with a paid one.
