### ISSUE TITLE
Windows Opens With Black Screen?

### ISSUE THREAD

**Issue by Soft-Bred** [utsanjan/PD-Runner#7]
Tried running Windows Through PD Runner and this is the window that pops up.

<img width="1758" alt="No 004252@2x" src="https://user-images.githubusercontent.com/60551230/186849217-0c562a2d-43dd-48b2-843f-b72aa4f59b21.png">

**Comment by utsanjan** [comment]
> Tried running Windows Through PD Runner and this is the window that pops up.
> 
> 
> 
> <img width="1758" alt="No 004252@2x" src="https://user-images.githubusercontent.com/60551230/186849217-0c562a2d-43dd-48b2-843f-b72aa4f59b21.png">
> 
> 

Have you tried enabling the trial period from the parallels desktop app?

**Comment by Soft-Bred** [comment]
that is what I've been using from the start, just randomly decided to stop working today

**Comment by utsanjan** [comment]
Ok I'll look into this, but most probably its because of any broken system updates or something, not sure though.

**Comment by utsanjan** [comment]
This issue is fixed now in the new 0.3.8 patched version. And yes, do follow the new usage guide from the ReadMe for it to work perfectly.
